Refactor admin permissions endpoint to accept array of permissions
Redseal-RepairFind/repairfind-be pull request #14
Opened 2024-10-04 16:05 UTC by holabayor

Refactored admin permissions endpoint to accept array of permissions and return improved response for the frontend

2024-10-04 16:25 UTC, AironDev requested changes

2024-10-04 16:25 UTC, AironDev commented on src/modules/admin/controllers/admin_staff.controller.ts
> +        if (existingPermissions.length === newPermissions.length) {
This is not needed

2024-10-04 16:25 UTC, AironDev commented on src/modules/admin/controllers/admin_staff.controller.ts
> -                .status(401)
Empty valid permissions can be used to clear all permissions from the staff.

2024-10-04 16:44 UTC, holabayor commented on src/modules/admin/controllers/admin_staff.controller.ts
> +        if (existingPermissions.length === newPermissions.length) {
That's the only way I'd know if a new permission was added or the same permissions are being added again.

2024-10-04 16:45 UTC, holabayor commented on src/modules/admin/controllers/admin_staff.controller.ts
> -                .status(401)
line 256-262 will validate each permission and check if it's not empty

2024-10-07 21:14 UTC, RepairFind-CA approved these changes

2024-10-07 21:14 UTC, merged